# Load Packages

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pickle as pickle
from sklearn.preprocessing import OrdinalEncoder, StandardScaler
from sklearn import svm
from sklearn.metrics import matthews_corrcoef, make_scorer, ConfusionMatrixDisplay
from sklearn.model_selection import GridSearchCV

from classical_data_processing import get_vectorized_data

# Import Data

In [2]:
X_train, y_train, X_val, y_val, X_test, y_test = get_vectorized_data()

In [5]:
class_names = pd.read_csv("../data/class_names.csv", index_col=0).to_numpy()
class_names

array([['Irrelevant'],
       ['Negative'],
       ['Neutral'],
       ['Positive']], dtype=object)

In [6]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(87596, 1022))

In [7]:
X_val

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(1500, 1358))

In [8]:
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(1000, 1703))

# Model

In [ ]:
svc = svm.LinearSVC(random_state=42)
matthews_scorer = make_scorer(matthews_corrcoef)

## Hyperparameter Search

In [ ]:
param_grid = {
    "loss": ["hinge", "squared_hinge"],
    "dual": [True, False],
    "C": [0.01, 0.1, 0.5, 1.0],
    "max_iter": [500, 1000, 2000, 5000, 10000, 20000]
}

grid_search = GridSearchCV(svc, param_grid, scoring=matthews_scorer, verbose=3)
grid_search.fit(X_train, y_train)

grid_search.cv_results_

In [ ]:
best_model = grid_search.best_estimator_

## Training Evaluation

In [ ]:
train_score = best_model.score(X_train, y_train)

print("Training Score: ", train_score)

## Validation

In [ ]:
val_score = best_model.score(X_val, y_val)

print("Validation Score: ", val_score)

## Test Evaluation

In [ ]:
test_score = best_model.score(X_test, y_test)

print("Test Score: ", test_score)

# Display Results

In [ ]:
titles = [
    ("Confusion Matrix (without normalization)", None),
    ("Confusion Matrix (normalized)", "true")
]

display = ConfusionMatrixDisplay.from_estimator(
    best_model,
    xval,
    yval,
    display_labels=class_names,
    cmap=plt.cm.Blues,
    normalize="true"
)